(() => {
    'use strict';

    const KEYS = { users: 'manageMyShifts.users', shifts: 'manageMyShifts.shifts', session: 'manageMyShifts.session' };
    const app = document.querySelector('#app');
    const state = { view: 'dashboard', authView: 'login', editingId: null, filters: { search: '', from: '', to: '' } };

    const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
    const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
    const users = () => read(KEYS.users, []);
    const shifts = () => read(KEYS.shifts, []);
    const session = () => read(KEYS.session, null);
    const currentUser = () => users().find((user) => user.id === session()?.userId);
    const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
    const formatMoney = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value || 0);
    const calculateHours = (start, end) => { const [sh, sm] = start.split(':').map(Number); const [eh, em] = end.split(':').map(Number); let minutes = (eh * 60 + em) - (sh * 60 + sm); if (minutes < 0) minutes += 1440; return minutes / 60; };
    const dateLabel = (date) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${date}T12:00:00`));
    const toast = (message, type = 'info') => { const element = document.createElement('div'); element.className = `toast ${type}`; element.textContent = message; document.querySelector('#toast-region').append(element); setTimeout(() => element.remove(), 3200); };

    function validateCredentials(username, password) {
        if (username.length < 6 || password.length < 6) return 'Username and password must have at least 6 characters.';
        if (!/[A-Za-z]/.test(username) || !/\d/.test(username) || !/[^A-Za-z\d]/.test(username)) return 'Username must contain letters, numbers and a special character.';
        return '';
    }

    function render() { if (!currentUser()) renderAuth(); else renderShell(); }

    function renderAuth() {
        const isRegister = state.authView === 'register';
        app.innerHTML = `<main class="auth-layout"><section class="auth-intro"><div class="company-logo-frame"><img class="company-logo" src="public/exer-tech.png" alt="Exer-Tech Services Inc. logo"></div><span class="brand-mark">MM</span><p class="kicker">Manage My Shifts</p><h1>Make every hour count.</h1><p class="intro-copy">A clear home for your working hours, wages, and monthly earnings.</p><div class="intro-rule"></div><p class="intro-note">Your records stay on this device with local storage.</p></section><section class="auth-panel"><div class="auth-heading"><p class="kicker">${isRegister ? 'New account' : 'Welcome back'}</p><h2>${isRegister ? 'Create your account' : 'Sign in to your workspace'}</h2></div><div class="auth-tabs"><button class="${!isRegister ? 'active' : ''}" data-auth="login">Sign in</button><button class="${isRegister ? 'active' : ''}" data-auth="register">Register</button></div>${isRegister ? registerForm() : loginForm()}</section></main>`;
        app.querySelectorAll('[data-auth]').forEach((button) => button.addEventListener('click', () => { state.authView = button.dataset.auth; render(); }));
        app.querySelector('form').addEventListener('submit', isRegister ? register : login);
        app.querySelector('[data-forgot]')?.addEventListener('click', resetAccount);
    }

    const input = (label, name, type = 'text', required = true, extra = '') => `<label class="field"><span>${label}</span><input name="${name}" type="${type}" ${required ? 'required' : ''} ${extra}></label>`;
    function loginForm() { return `<form class="form-stack"><p class="auth-help">Use your registered username and password. Both must contain at least 6 characters.</p>${input('Username', 'username', 'text', true, 'minlength="6" autocomplete="username"')} ${input('Password', 'password', 'password', true, 'minlength="6" autocomplete="current-password"')}<button class="button primary wide" type="submit">Sign in <span>→</span></button><button class="text-button" type="button" data-forgot>Forgot password? Reset local account</button></form>`; }
    function registerForm() { return `<form class="form-stack">${input('Email', 'email', 'email')}<div class="form-row">${input('First name', 'firstName', 'text', true, 'minlength="2"')} ${input('Last name', 'lastName', 'text', true, 'minlength="2"')}</div>${input('Username', 'username', 'text', true, 'minlength="6" autocomplete="username"')}<div class="form-row">${input('Password', 'password', 'password', true, 'minlength="6" autocomplete="new-password"')} ${input('Confirm password', 'confirmPassword', 'password', true, 'minlength="6"')}</div>${input('Birth date', 'birthDate', 'date')}<button class="button primary wide" type="submit">Create account <span>→</span></button></form>`; }

    function register(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const credentialError = validateCredentials(data.username, data.password); const age = (Date.now() - new Date(data.birthDate).getTime()) / 31557600000; if (credentialError) return toast(credentialError, 'error'); if (data.password !== data.confirmPassword) return toast('Passwords do not match.', 'error'); if (age < 18 || age > 65) return toast('Age must be between 18 and 65.', 'error'); if (users().some((user) => user.username.toLowerCase() === data.username.toLowerCase())) return toast('That username is already registered.', 'error'); const user = { id: uid(), email: data.email, username: data.username, password: data.password, firstName: data.firstName, lastName: data.lastName, birthDate: data.birthDate }; write(KEYS.users, [...users(), user]); write(KEYS.session, { userId: user.id, expiresAt: Date.now() + 3600000 }); toast('Account created. Welcome!', 'success'); render(); }
    function login(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const user = users().find((item) => item.username.toLowerCase() === data.username.toLowerCase() && item.password === data.password); if (!user) return toast('Incorrect username or password.', 'error'); write(KEYS.session, { userId: user.id, expiresAt: Date.now() + 3600000 }); render(); }
    function resetAccount() { if (!confirm('Resetting your password will delete all local account data. Continue?')) return; localStorage.removeItem(KEYS.users); localStorage.removeItem(KEYS.shifts); localStorage.removeItem(KEYS.session); toast('Local account data deleted.', 'success'); render(); }

    function renderShell() { const user = currentUser(); const visibleShifts = getVisibleShifts(); app.innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="sidebar-brand"><span class="brand-mark">MM</span><span>Manage My<br><b>Shifts</b></span></div><nav><button class="nav-item ${state.view === 'dashboard' ? 'active' : ''}" data-view="dashboard"><span>▦</span> My shifts</button><button class="nav-item ${state.view === 'add' ? 'active' : ''}" data-view="add"><span>＋</span> Add shift</button><button class="nav-item ${state.view === 'profile' ? 'active' : ''}" data-view="profile"><span>◎</span> My profile</button></nav><button class="nav-item logout" data-logout><span>↪</span> Log out</button></aside><main class="main-content"><header class="topbar"><div><p class="kicker">${state.view === 'dashboard' ? 'Overview' : state.view === 'add' ? 'Time entry' : 'Account settings'}</p><h1>${state.view === 'dashboard' ? 'My shifts' : state.view === 'add' ? (state.editingId ? 'Edit shift' : 'Add a shift') : 'My profile'}</h1></div><div class="user-menu"><span class="avatar">${escapeHtml(user.firstName[0])}${escapeHtml(user.lastName[0])}</span><span>Hello, <b>${escapeHtml(user.username)}</b></span></div></header>${state.view === 'dashboard' ? dashboard(visibleShifts) : state.view === 'add' ? shiftForm() : profileForm()}</main></div>`; bindShell(); }
    function bindShell() { app.querySelectorAll('[data-view]').forEach((button) => button.addEventListener('click', () => { state.view = button.dataset.view; state.editingId = null; render(); })); app.querySelector('[data-logout]').addEventListener('click', () => { localStorage.removeItem(KEYS.session); state.view = 'dashboard'; render(); }); app.querySelector('[data-search]')?.addEventListener('input', (event) => { state.filters.search = event.target.value; renderShell(); }); app.querySelectorAll('[data-filter]').forEach((el) => el.addEventListener('change', (event) => { state.filters[event.target.name] = event.target.value; renderShell(); })); app.querySelector('[data-shift-form]')?.addEventListener('submit', saveShift); app.querySelector('[data-profile-form]')?.addEventListener('submit', updateProfile); app.querySelectorAll('[data-edit]').forEach((button) => button.addEventListener('click', () => { state.editingId = button.dataset.edit; state.view = 'add'; render(); })); app.querySelectorAll('[data-delete]').forEach((button) => button.addEventListener('click', () => deleteShift(button.dataset.delete))); }

    function getVisibleShifts() { const user = currentUser(); return shifts().filter((shift) => shift.userId === user.id).filter((shift) => !state.filters.search || `${shift.slug} ${shift.workplace} ${shift.comments}`.toLowerCase().includes(state.filters.search.toLowerCase())).filter((shift) => !state.filters.from || shift.date >= state.filters.from).filter((shift) => !state.filters.to || shift.date <= state.filters.to).sort((a, b) => b.date.localeCompare(a.date)); }
    function dashboard(visible) { const total = visible.reduce((sum, shift) => sum + shift.profit, 0); const monthTotals = visible.reduce((map, shift) => map.set(shift.date.slice(0, 7), (map.get(shift.date.slice(0, 7)) || 0) + shift.profit), new Map()); const best = [...monthTotals.entries()].sort((a, b) => b[1] - a[1])[0]; return `<section class="stats-grid"><div class="stat-card accent"><span>Total earnings</span><strong>${formatMoney(total)}</strong><small>${visible.length} shift${visible.length === 1 ? '' : 's'} in view</small></div><div class="stat-card"><span>Total hours</span><strong>${visible.reduce((sum, shift) => sum + shift.hours, 0).toFixed(1)}</strong><small>hours worked</small></div><div class="stat-card"><span>Best month</span><strong>${best ? formatMoney(best[1]) : '$0.00'}</strong><small>${best ? new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(new Date(`${best[0]}-15T12:00:00`)) : 'No data yet'}</small></div></section><section class="content-panel"><div class="panel-header"><div><p class="kicker">Your activity</p><h2>Shift history</h2></div><button class="button primary" data-view="add">＋ Add shift</button></div><div class="filters"><input data-search placeholder="Search workplace or shift name" value="${escapeHtml(state.filters.search)}"><label>From <input data-filter name="from" type="date" value="${state.filters.from}"></label><label>To <input data-filter name="to" type="date" value="${state.filters.to}"></label></div>${visible.length ? `<div class="table-wrap"><table><thead><tr><th>Date</th><th>Shift</th><th>Workplace</th><th>Hours</th><th>Wage</th><th>Profit</th><th></th></tr></thead><tbody>${visible.map(shiftRow).join('')}</tbody></table></div>` : '<div class="empty-state"><span>◷</span><h3>No shifts found</h3><p>Add your first shift or adjust the filters.</p><button class="button secondary" data-view="add">Add a shift</button></div>'}</section>`; }
    function shiftRow(shift) { return `<tr><td><b>${dateLabel(shift.date)}</b></td><td><b>${escapeHtml(shift.slug)}</b><small>${shift.startTime} - ${shift.endTime}</small></td><td>${escapeHtml(shift.workplace)}</td><td>${shift.hours.toFixed(1)}h</td><td>${formatMoney(shift.wage)}/h</td><td class="profit">${formatMoney(shift.profit)}</td><td><div class="row-actions"><button class="icon-button" title="Edit shift" data-edit="${shift.id}">✎</button><button class="icon-button danger" title="Delete shift" data-delete="${shift.id}">×</button></div></td></tr>`; }
    function shiftForm() { const shift = shifts().find((item) => item.id === state.editingId) || {}; return `<section class="form-panel"><div class="panel-header"><div><p class="kicker">${state.editingId ? 'Update record' : 'New record'}</p><h2>${state.editingId ? 'Edit your shift' : 'Record a working shift'}</h2></div></div><form class="form-stack" data-shift-form><div class="form-row">${input('Date', 'date', 'date', true, `value="${shift.date || ''}"`)}${input('Shift name', 'slug', 'text', true, `value="${escapeHtml(shift.slug || '')}" placeholder="e.g. Monday opening"`)}</div><div class="form-row">${input('Start time', 'startTime', 'time', true, `value="${shift.startTime || ''}"`)}${input('End time', 'endTime', 'time', true, `value="${shift.endTime || ''}"`)}${input('Hourly wage', 'wage', 'number', true, `min="0" step="0.01" value="${shift.wage || ''}" placeholder="0.00"`)}</div><label class="field"><span>Workplace</span><select name="workplace" required><option value="">Choose a workplace</option>${['Main office', 'Remote', 'Client site', 'Other'].map((place) => `<option ${shift.workplace === place ? 'selected' : ''}>${place}</option>`).join('')}</select></label><label class="field"><span>Comments <em>optional</em></span><textarea name="comments" rows="4" placeholder="Add a note about this shift">${escapeHtml(shift.comments || '')}</textarea></label><div class="form-actions"><button class="button primary" type="submit">${state.editingId ? 'Update shift' : 'Save shift'} <span>→</span></button><button class="button secondary" type="button" data-view="dashboard">Cancel</button></div></form></section>`; }
    function saveShift(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const ownShifts = shifts().filter((shift) => shift.userId === currentUser().id); if (ownShifts.some((shift) => shift.slug.toLowerCase() === data.slug.toLowerCase() && shift.id !== state.editingId)) return toast('Each shift name must be unique.', 'error'); const hours = calculateHours(data.startTime, data.endTime); if (!hours) return toast('Start and end time cannot be the same.', 'error'); const record = { id: state.editingId || uid(), userId: currentUser().id, ...data, wage: Number(data.wage), hours, profit: hours * Number(data.wage) }; const next = state.editingId ? shifts().map((shift) => shift.id === state.editingId ? record : shift) : [...shifts(), record]; write(KEYS.shifts, next); state.editingId = null; state.view = 'dashboard'; toast('Shift saved successfully.', 'success'); render(); }
    function deleteShift(id) { if (!confirm('Delete this shift?')) return; write(KEYS.shifts, shifts().filter((shift) => shift.id !== id)); toast('Shift deleted.', 'success'); render(); }
    function profileForm() { const user = currentUser(); return `<section class="form-panel"><div class="panel-header"><div><p class="kicker">Personal details</p><h2>Edit your profile</h2></div></div><form class="form-stack" data-profile-form>${input('Email', 'email', 'email', true, `value="${escapeHtml(user.email)}"`)}<div class="form-row">${input('First name', 'firstName', 'text', true, `minlength="2" value="${escapeHtml(user.firstName)}"`)}${input('Last name', 'lastName', 'text', true, `minlength="2" value="${escapeHtml(user.lastName)}"`)}</div>${input('Username', 'username', 'text', true, `minlength="6" value="${escapeHtml(user.username)}"`)}<div class="form-row">${input('New password', 'password', 'password', true, 'minlength="6" placeholder="Enter password"')}${input('Confirm password', 'confirmPassword', 'password', true, 'minlength="6" placeholder="Repeat password"')}</div>${input('Birth date', 'birthDate', 'date', true, `value="${user.birthDate}"`)}<div class="form-actions"><button class="button primary" type="submit">Update profile <span>→</span></button></div></form></section>`; }
    function updateProfile(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const user = currentUser(); const credentialError = validateCredentials(data.username, data.password); const age = (Date.now() - new Date(data.birthDate).getTime()) / 31557600000; if (credentialError) return toast(credentialError, 'error'); if (data.password !== data.confirmPassword) return toast('Passwords do not match.', 'error'); if (age < 18 || age > 65) return toast('Age must be between 18 and 65.', 'error'); const duplicate = users().some((item) => item.id !== user.id && item.username.toLowerCase() === data.username.toLowerCase()); if (duplicate) return toast('That username is already registered.', 'error'); write(KEYS.users, users().map((item) => item.id === user.id ? { ...item, ...data } : item)); toast('Profile updated.', 'success'); state.view = 'dashboard'; render(); }

    const activeSession = session(); if (activeSession && activeSession.expiresAt < Date.now()) localStorage.removeItem(KEYS.session); render();
})();